
spring:
  datasource:
    url: jdbc:postegresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDAte
    username:  postgres
    password: 12345
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
        properties:
          hibernate.format_sql: true

logging:
  level:
    org:
      hibenate:
        type: trace


